version: 2.1

executors:
  gradle-executor:
    docker:
      - image: gradle:4.10-jdk8

jobs:
  build:
    executor: gradle-executor

    steps:
      - checkout

      - restore_cache:
         keys:
           - v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies
      - run: gradle setupCiWorkspace

      - save_cache:
         paths:
           - ~/.gradle
         key: v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle build

      - store_artifacts:
         path: common/build/libs

      - store_artifacts:
         path: forge/build/libs

  test:
    executor: gradle-executor

    steps:
      - checkout

      - restore_cache:
         keys:
          - v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies
      - run: gradle setupCiWorkspace
      - run: gradle test

  deploy:
    executor: gradle-executor

    steps:
      - checkout

      - restore_cache:
         keys:
          - v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies
      - run: gradle setupCiWorkspace
      - run: gradle artifactoryPublish

  notify-dev:
    executor: gradle-executor

    steps:
      - checkout
      - run: bash .circleci/send-dev-notification.sh

workflows:
  build-test-deploy:
    jobs:
      - build
      - test
      - deploy:
         requires:
           - build
           - test
         filters:
           branches:
             only:
               - dev
               - master
  nightly:
    triggers:
      - schedule:
          cron: "0 20 * * *"
          filters:
            branches:
              only:
                - dev
    jobs:
      - notify-dev
