version: 2

jobs:
  build:
    docker:
      - image: gradle:4.10-jdk8

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
        keys:
          - v2-dependencies-{{ checksum "build.gradle" }}
          - v2-dependencies-

      - run: gradle dependencies

      - run: gradle setupCiWorkspace

      - save_cache:
        paths:
            - ~/.gradle
        key: v1-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test
