version: 2.1

jobs:
  build:
    docker:
      - image: gradle:4.10-jdk8

    steps:
      - checkout

      - run: echo $(git log --format=%B -n 1 $CIRCLE_SHA1)

      - restore_cache:
         keys:
           - v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies
      - run: gradle setupCiWorkspace

      - save_cache:
         paths:
           - ~/.gradle
         key: v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle build

      - store_artifacts:
         path: common/build/libs

      - store_artifacts:
         path: forge/build/libs

  test:
    docker:
      - image: gradle:4.10-jdk8

    steps:
      - checkout

      - restore_cache:
         keys:
          - v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies
      - run: gradle setupCiWorkspace
      - run: gradle test

  deploy:
    docker:
      - image: gradle:4.10-jdk8

    environment:
      GIT_COMMIT_DESC: git log --format=%B -n 1 $CIRCLE_SHA1

    steps:
      - checkout

      - restore_cache:
         keys:
          - v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies
      - run: gradle setupCiWorkspace
      - run: gradle artifactoryPublish

      - run: >
          curl -H "Content-Type: application/json"
          -X POST $DISCORD_DEV_URL
          -d
          "
          {
          	\"content\": \"\",
          	\"embeds\": [{
          		\"title\": \"A New Developer Build is Available for Use\",
          		\"description\": \"$GIT_COMMIT_DESC\",
          		\"url\": \"https://artifactory.feldman.tech/artifactory/webapp/#/artifacts/browse/tree/General/minecraft/com/codingforcookies/betterrecords/BetterRecords-forge/1.12.2-SNAPSHOT/maven-metadata.xml\",
          		\"color\": 2068783
          	}]
          }
          "

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test
      - deploy:
         requires:
           - build
           - test
         filters:
           branches:
             only:
               - dev
               - master
