version: 2.1

jobs:
  build:
    docker:
      - image: gradle:4.10-jdk8

    steps:
      - checkout

      - restore_cache:
         keys:
           - v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies
      - run: gradle setupCiWorkspace

      - save_cache:
         paths:
           - ~/.gradle
         key: v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle build

      - store_artifacts:
         path: common/build/libs

      - store_artifacts:
         path: forge/build/libs

  test:
    docker:
      - image: gradle:4.10-jdk8

    steps:
      - checkout

      - restore_cache:
         keys:
          - v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies
      - run: gradle setupCiWorkspace
      - run: gradle test

  deploy:
    docker:
      - image: gradle:4.10-jdk8

    steps:
      - checkout

      - restore_cache:
         keys:
          - v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies
      - run: gradle setupCiWorkspace
      - run: gradle artifactoryPublish

      - run: bash .circleci/send-dev-notification.sh

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test
      - deploy:
         requires:
           - build
           - test
         filters:
           branches:
             only:
               - dev
               - master
