version: 2

jobs:
  build:
    docker:
      - image: gradle:4.10-jdk8

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - restore_cache:
         keys:
           - v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle dependencies

      - run: gradle setupCiWorkspace

      - save_cache:
         paths:
           - ~/.gradle
         key: v2-dependencies-{{ checksum "build.gradle" }}

      - run: gradle test

      - run: gradle build

      - store_artifacts:
         path: common/build/libs

      - store_artifacts:
         path: forge/build/libs
