name: Check License Headers

on: [push, pull_request]

jobs:
  license:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Grande execute permission for gradlew
        run: chmod +x gradlew
      - name: Check license headers with Gradle
        run: ./gradlew license
